variables:
  DEPS: build-essential git wget
  WANT_BUILD_DEPS: "true"

# For the smoke tests we also want debug packages, wlroots/rootston,
# weston-info, gdb, valgrind, ...
.smoketest_vars:
  variables: &smoketest_vars
    DEPS: libwlroots-examples wget gnome-session gdb weston valgrind
          libhandy-0.0-0-dbgsym libgtk-3-0-dbgsym libglib2.0-0-dbgsym
          dconf-gsettings-backend-dbgsym
          xvfb imagemagick
    WANT_BUILD_DEPS: "false"

before_script:
  - export DEBIAN_FRONTEND=noninteractive
  - apt-get -y update
  - apt-get -y install wget ca-certificates gnupg eatmydata
  - echo "deb http://ci.puri.sm/ scratch librem5" > /etc/apt/sources.list.d/ci.list
  - wget -O- https://ci.puri.sm/ci-repo.key | apt-key add -
  - echo "deb http://debug.mirrors.debian.org/debian-debug/ buster-debug main" > /etc/apt/sources.list.d/debug.list
  - eatmydata apt-get -y update
  - '[ "$WANT_BUILD_DEPS" != "true" ] || eatmydata apt-get -y build-dep .'
  - eatmydata apt-get -y install $DEPS
  - ulimit -c unlimited

.tags: &tags
  tags:
    - librem5

build:native:
  <<: *tags
  stage: build
  artifacts:
    paths:
      - _build
  script:
    - meson --werror . _build
    - ninja -C _build

test:native:
  <<: *tags
  stage: test
  dependencies:
    - build:native
  script:
    - export LC_ALL=C.UTF-8
    - xvfb-run ninja -C _build test

test:smoke:one-output:
  <<: *tags
  stage: test
  variables: *smoketest_vars
  dependencies:
    - build:native
  script:
    - export OUTDIR=output
    - export G_DEBUG=fatal-criticals
    - export WLR_X11_OUTPUTS=1
    - tests/smoke
  artifacts:
    paths:
      - output/*.log
      - output/*.png
    when: always

test:smoke:two-outputs:
  <<: *tags
  stage: test
  variables: *smoketest_vars
  dependencies:
    - build:native
  script:
    - export OUTDIR=output
    - export G_DEBUG=fatal-criticals
    - export WLR_X11_OUTPUTS=2
    - tests/smoke
  artifacts:
    paths:
      - output/*.log
      - output/*.png
    when: always

test:smoke:valgrind:
  <<: *tags
  stage: test
  variables: *smoketest_vars
  dependencies:
    - build:native
  script:
    - export OUTDIR=output
    - export G_DEBUG=fatal-criticals
    - export WLR_X11_OUTPUTS=1
    - tests/smoke -V -T 30
  artifacts:
    paths:
      - vgdump
      - output/*.log
      - output/*.png
    when: always

