include:
 - 'https://source.puri.sm/Librem5/librem5-ci/raw/master/librem5-pipeline-definitions.yml'

stages:
 - build
 - test
 - package
 - test-package

variables:
  DEPS: build-essential git wget lcov
  WANT_BUILD_DEPS: "true"

# For the smoke tests we also want debug packages, phoc,
# weston-info, gdb, valgrind, ...
.smoketest_vars:
  variables: &smoketest_vars
    DEPS: phoc wget gnome-session gdb weston valgrind
          libhandy-0.0-0-dbgsym libgtk-3-0-dbgsym libglib2.0-0-dbgsym
          dconf-gsettings-backend-dbgsym
          xvfb imagemagick
    WANT_BUILD_DEPS: "false"

before_script:
  - export DEBIAN_FRONTEND=noninteractive
  - apt-get -y update
  - apt-get -y install wget ca-certificates gnupg eatmydata
  - echo "deb http://ci.puri.sm/ scratch librem5" > /etc/apt/sources.list.d/ci.list
  - wget -O- https://ci.puri.sm/ci-repo.key | apt-key add -
  - echo "deb http://debug.mirrors.debian.org/debian-debug/ buster-debug main" > /etc/apt/sources.list.d/debug.list
  - eatmydata apt-get -y update
  - '[ "$WANT_BUILD_DEPS" != "true" ] || eatmydata apt-get -y build-dep .'
  - eatmydata apt-get -y install $DEPS
  - ulimit -c unlimited

.tags: &tags
  tags:
    - librem5

build:native-debian-buster:
  <<: *tags
  stage: build
  image: debian:buster
  artifacts:
    paths:
      - _build
  script:
    - git submodule update --recursive
    - meson -Db_coverage=true --werror . _build
    - ninja -C _build

unit-test:native-debian-buster:
  <<: *tags
  stage: test
  image: debian:buster
  dependencies:
    - build:native-debian-buster
  script:
    - export LC_ALL=C.UTF-8
    - xvfb-run ninja -C _build test coverage
  coverage: '/^\s+lines\.+:\s+([\d.]+\%)\s+/'
  artifacts:
    when: always
    paths:
      - _build

build:native-debian-bullseye:
  <<: *tags
  stage: build
  image: debian:bullseye
  artifacts:
    paths:
      - _build
  script:
    - git submodule update --recursive
    - meson -Db_coverage=true --werror . _build
    - ninja -C _build

unit-test:native-debian-bullseye:
  <<: *tags
  stage: test
  image: debian:bullseye
  dependencies:
    - build:native-debian-bullseye
  script:
    - export LC_ALL=C.UTF-8
    - xvfb-run ninja -C _build test coverage
  coverage: '/^\s+lines\.+:\s+([\d.]+\%)\s+/'
  artifacts:
    when: always
    paths:
      - _build

build:native-alpinelinux-edge:
  <<: *tags
  stage: build
  image: alpine:edge
  allow_failure: true
  before_script:
    - apk -q add alpine-sdk
    - apk -q add meson ninja gtk+3.0-dev gnome-desktop-dev libhandy-dev gcr-dev upower-dev linux-pam-dev git pulseaudio-dev networkmanager-dev polkit-elogind-dev libsecret-dev
  artifacts:
    paths:
      - _build
  script:
    - git submodule update --recursive
    - meson --werror . _build
    - ninja -C _build

unit-test:native-alpinelinux-edge:
  <<: *tags
  stage: test
  image: alpine:edge
  allow_failure: true
  dependencies:
    - build:native-alpinelinux-edge
  before_script:
    - apk -q add alpine-sdk
    - apk -q add xvfb-run meson ninja glib-dev wayland-protocols wayland-dev musl-dev gnome-desktop-dev libhandy-dev gcr-dev upower-dev linux-pam-dev pulseaudio-dev networkmanager-dev polkit-elogind-dev libsecret-dev gcovr
  script:
    - export LC_ALL=C.UTF-8
    - xvfb-run ninja -C _build test
  artifacts:
    when: always
    paths:
      - _build

test:smoke:one-output:
  <<: *tags
  stage: test
  image: debian:buster
  variables: *smoketest_vars
  dependencies:
    - build:native-debian-buster
  script:
    - export OUTDIR=output
    - export G_DEBUG=fatal-criticals
    - export WLR_X11_OUTPUTS=1
    - tests/smoke
  artifacts:
    paths:
      - output/*.log
      - output/*.png
    when: always

test:smoke:two-outputs:
  <<: *tags
  stage: test
  image: debian:buster
  variables: *smoketest_vars
  dependencies:
    - build:native-debian-buster
  script:
    - export OUTDIR=output
    - export G_DEBUG=fatal-criticals
    - export WLR_X11_OUTPUTS=2
    - tests/smoke
  artifacts:
    paths:
      - output/*.log
      - output/*.png
    when: always

package:deb-debian-buster:
  extends: .l5-build-debian-package

package:deb-pureos-amber:
  variables:
    L5_DOCKER_IMAGE: pureos/amber
    L5_ADD_SCRATCH_CI: 'false'
  extends: .l5-build-debian-package

autopkgtest-debian-buster-package:
  dependencies:
    - package:deb-debian-buster
  extends: .l5-autopkgtest-debian-package

lintian-debian-buster-package:
  dependencies:
    - package:deb-debian-buster
  extends: .l5-lintian-debian-package

